all:
  hosts:
    app_servers:
      ansible_host: <App_Public_IP>
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa

    db_servers:
      ansible_host: <DB_Public_IP>
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
